"""
Embedding — SQLAlchemy model for persisted embedding vectors (Day 69 Part A2).

Relationships:
    User 1 ──── * Embedding
    ParsedDocument 1 ──── * Embedding
    Chunk 1 ──── * Embedding

One chunk may have multiple embeddings across different providers/models/versions,
but only one active (non-ARCHIVED) embedding should exist per:
    (chunk_id, provider, model_name, model_version, embedding_version)

Status lifecycle:
    PENDING    → PROCESSING  (embedding generation started)
    PROCESSING → READY       (vector generated and validated successfully)
    PROCESSING → FAILED      (provider error or validation failure)
    READY      → ARCHIVED    (superseded by newer embedding)
    FAILED     → PROCESSING  (retry attempt)

Future:
    ARCHIVED → (new READY embedding created for same chunk)
    READY    → INDEXED (Day 70: stored in vector index)

Security:
    - user_id is denormalised for O(1) ownership queries.
    - vector field must never be exposed in API responses.
    - provider credentials are never stored in this table.
"""
from __future__ import annotations

import enum
import json
import uuid
from datetime import datetime
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


# ── Enums ─────────────────────────────────────────────────────────────────────

class EmbeddingStatus(str, enum.Enum):
    """
    Lifecycle status of a persisted embedding.

    PENDING    — embedding record created, generation not started.
    PROCESSING — actively being generated by the embedding provider.
    READY      — vector is valid and available for vector storage (Day 70).
    FAILED     — generation failed; may be retried.
    ARCHIVED   — superseded by a newer embedding (model/version upgrade).
    """

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


# ── Model ─────────────────────────────────────────────────────────────────────

class Embedding(Base):
    """
    One persisted embedding vector for one semantic chunk.

    The vector is stored as a JSON-serialised list[float] in a Text column.
    This keeps the architecture simple for Day 69 and allows Day 70 to
    introduce pgvector or a dedicated vector store without any schema conflict.

    Ownership chain: User → Document → ParsedDocument → Chunk → Embedding

    Vector field notes:
        - Use the helper property `get_vector()` / `set_vector()` for safe access.
        - Never log or serialize the vector to API responses.
        - The raw `_vector_json` column is internal.

    Idempotency guarantee:
        The UniqueConstraint on (chunk_id, provider, model_name, model_version,
        embedding_version) prevents duplicate active embeddings. Archived rows
        are logically excluded by the application before insertion.
    """

    __tablename__ = "embeddings"

    # ── Identity ──────────────────────────────────────────────────────────────

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID v4 — unique embedding identifier.",
    )

    # ── Ownership ─────────────────────────────────────────────────────────────

    chunk_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("chunks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Parent Chunk. CASCADE delete removes embeddings when chunk is deleted.",
    )

    parsed_document_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("parsed_documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Denormalised for efficient document-level queries.",
    )

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Denormalised owner user_id for O(1) ownership queries.",
    )

    # ── Provider / Model Metadata ─────────────────────────────────────────────

    provider: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Short provider name (e.g. 'gemini', 'openai').",
    )

    model_name: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="Canonical model identifier (e.g. 'text-embedding-004').",
    )

    model_version: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        comment="Provider-level model version tag (e.g. 'v1').",
    )

    embedding_version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        comment="Application-level embedding strategy version. Increment on strategy changes.",
    )

    # ── Vector Data ───────────────────────────────────────────────────────────

    dimension: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Number of float values in the vector. Provider-defined.",
    )

    _vector_json: Mapped[Optional[str]] = mapped_column(
        "vector_json",
        Text,
        nullable=True,
        comment=(
            "JSON-serialised list[float]. "
            "Null for PENDING/PROCESSING/FAILED records. "
            "Day 70 will introduce pgvector/FAISS for indexed search."
        ),
    )

    # ── Status ────────────────────────────────────────────────────────────────

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=EmbeddingStatus.PENDING.value,
        comment="Embedding lifecycle status.",
    )

    # ── Failure Tracking ──────────────────────────────────────────────────────

    failure_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of failed generation attempts for this embedding record.",
    )

    error_category: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        comment=(
            "Normalised error category on failure: "
            "'rate_limit', 'timeout', 'provider_error', 'validation_error'."
        ),
    )

    # ── Timestamps ────────────────────────────────────────────────────────────

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
        comment="When this embedding record was created.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
        nullable=False,
        comment="Last status update.",
    )

    archived_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Set when status transitions to ARCHIVED. NULL = active.",
    )

    # ── Relationships ─────────────────────────────────────────────────────────

    chunk = relationship(
        "Chunk",
        foreign_keys=[chunk_id],
    )

    parsed_document = relationship(
        "ParsedDocument",
        foreign_keys=[parsed_document_id],
    )

    user = relationship(
        "User",
        foreign_keys=[user_id],
    )

    # ── Indexes & Constraints ──────────────────────────────────────────────────

    __table_args__ = (
        # Composite uniqueness: prevents duplicate active embeddings.
        # Application MUST archive the old embedding before inserting a new one
        # with the same identity to avoid constraint violations.
        UniqueConstraint(
            "chunk_id",
            "provider",
            "model_name",
            "model_version",
            "embedding_version",
            name="uq_embedding_chunk_model_version",
        ),
        # Query-pattern indexes
        Index("idx_embedding_chunk_id", "chunk_id"),
        Index("idx_embedding_parsed_document_id", "parsed_document_id"),
        Index("idx_embedding_user_id", "user_id"),
        Index("idx_embedding_status", "status"),
        Index("idx_embedding_model_name", "model_name"),
        Index("idx_embedding_embedding_version", "embedding_version"),
        Index("idx_embedding_chunk_status", "chunk_id", "status"),
        Index("idx_embedding_doc_status", "parsed_document_id", "status"),
        Index("idx_embedding_user_status", "user_id", "status"),
    )

    # ── Vector helpers ─────────────────────────────────────────────────────────

    def get_vector(self) -> list[float] | None:
        """
        Deserialise and return the embedding vector.

        Returns None if the vector has not yet been generated (PENDING/PROCESSING/FAILED).
        Never call this in a log statement.
        """
        if self._vector_json is None:
            return None
        return json.loads(self._vector_json)

    def set_vector(self, vector: list[float] | None) -> None:
        """Serialise and store the embedding vector."""
        if vector is None:
            self._vector_json = None
        else:
            self._vector_json = json.dumps(vector)

    def __repr__(self) -> str:
        return (
            f"<Embedding id={self.id!r} chunk_id={self.chunk_id!r} "
            f"model={self.model_name!r} v{self.embedding_version} "
            f"dim={self.dimension} status={self.status!r}>"
        )
