"""
SkillSwap Arena — Production Redis Infrastructure Package (Phase 6)
"""
from app.infrastructure.redis.client import redis_client, SafeRedis
from app.infrastructure.redis.keys import (
    rate_limit_key,
    presence_key,
    session_presence_pattern,
    booking_lock_key,
    session_lock_key,
    availability_cache_key,
    availability_pattern,
    profile_cache_key,
    analytics_cache_key,
    heatmap_cache_key,
    streak_cache_key,
    recommendations_cache_key,
    recommendations_pattern,
    session_state_key,
    idempotency_key,
    oauth_state_key,
    oauth_ticket_key,
)
from app.infrastructure.redis.health import check_redis_health
from app.infrastructure.redis.rate_limiter import (
    enforce_sliding_window_rate_limit,
    enforce_booking_rate_limit,
    enforce_auth_rate_limit,
    enforce_ws_rate_limit,
    enforce_action_rate_limit,
    enforce_ai_rate_limit,
    get_client_ip,
)
from app.infrastructure.redis.locks import (
    RedisDistributedLock,
    distributed_booking_lock,
    distributed_session_lock,
)
from app.infrastructure.redis.cache import (
    get_json,
    set_json,
    delete_keys,
    delete_pattern,
    invalidate_mentor_availability,
    invalidate_user_learning_data,
    invalidate_recommendations,
    invalidate_user_profile,
)
from app.infrastructure.redis.pubsub import (
    publish_event,
    publish_user_notification,
    start_pubsub_listener,
    stop_pubsub_listener,
)

__all__ = [
    "redis_client",
    "SafeRedis",
    "rate_limit_key",
    "presence_key",
    "session_presence_pattern",
    "booking_lock_key",
    "session_lock_key",
    "availability_cache_key",
    "availability_pattern",
    "profile_cache_key",
    "analytics_cache_key",
    "heatmap_cache_key",
    "streak_cache_key",
    "recommendations_cache_key",
    "recommendations_pattern",
    "session_state_key",
    "idempotency_key",
    "check_redis_health",
    "enforce_sliding_window_rate_limit",
    "enforce_booking_rate_limit",
    "enforce_auth_rate_limit",
    "enforce_ws_rate_limit",
    "enforce_action_rate_limit",
    "enforce_ai_rate_limit",
    "get_client_ip",
    "RedisDistributedLock",
    "distributed_booking_lock",
    "distributed_session_lock",
    "get_json",
    "set_json",
    "delete_keys",
    "delete_pattern",
    "invalidate_mentor_availability",
    "invalidate_user_learning_data",
    "invalidate_recommendations",
    "invalidate_user_profile",
    "publish_event",
    "publish_user_notification",
    "start_pubsub_listener",
    "stop_pubsub_listener",
]
