"""change_profile_avatar_url_and_bio_to_text

Revision ID: 0e912b0154ce
Revises: c60a1_add_session_summaries
Create Date: 2026-07-30 19:42:03.840477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e912b0154ce'
down_revision: Union[str, None] = 'c60a1_add_session_summaries'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('strong_topics', sa.JSON(), nullable=False),
    sa.Column('weak_topics', sa.JSON(), nullable=False),
    sa.Column('learning_interests', sa.JSON(), nullable=False),
    sa.Column('recommended_topics', sa.JSON(), nullable=False),
    sa.Column('learning_style', sa.Text(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('context_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_contexts_user_id', 'ai_contexts', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_contexts_user_id'), 'ai_contexts', ['user_id'], unique=True)
    op.drop_constraint(op.f('learning_sessions_uuid_key'), 'learning_sessions', type_='unique')
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('session_summaries', 'key_takeaways',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('session_summaries', 'strengths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('session_summaries', 'weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('session_summaries', 'follow_up_topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(op.f('session_summaries_session_id_key'), 'session_summaries', type_='unique')
    op.drop_constraint(op.f('session_summaries_uuid_key'), 'session_summaries', type_='unique')
    op.create_index('idx_session_summaries_created_at', 'session_summaries', ['created_at'], unique=False)
    op.create_index('idx_session_summaries_session_id', 'session_summaries', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_summaries_session_id'), 'session_summaries', ['session_id'], unique=True)
    op.create_index(op.f('ix_session_summaries_uuid'), 'session_summaries', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_summaries_uuid'), table_name='session_summaries')
    op.drop_index(op.f('ix_session_summaries_session_id'), table_name='session_summaries')
    op.drop_index('idx_session_summaries_session_id', table_name='session_summaries')
    op.drop_index('idx_session_summaries_created_at', table_name='session_summaries')
    op.create_unique_constraint(op.f('session_summaries_uuid_key'), 'session_summaries', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('session_summaries_session_id_key'), 'session_summaries', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('session_summaries', 'follow_up_topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('session_summaries', 'weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('session_summaries', 'strengths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('session_summaries', 'key_takeaways',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_unique_constraint(op.f('learning_sessions_uuid_key'), 'learning_sessions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ai_contexts_user_id'), table_name='ai_contexts')
    op.drop_index('idx_ai_contexts_user_id', table_name='ai_contexts')
    op.drop_table('ai_contexts')
    # ### end Alembic commands ###
