"""add user skill indexes

Revision ID: 6ab6041a0b5a
Revises: 2c737443f806
Create Date: 2026-06-17 12:23:33.891868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab6041a0b5a'
down_revision: Union[str, None] = '2c737443f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_skill_skill_id', 'user_skills', ['skill_id'], unique=False)
    op.create_index('idx_user_skill_type', 'user_skills', ['type'], unique=False)
    op.create_index('idx_user_skill_user_id', 'user_skills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_skill_user_id', table_name='user_skills')
    op.drop_index('idx_user_skill_type', table_name='user_skills')
    op.drop_index('idx_user_skill_skill_id', table_name='user_skills')
    # ### end Alembic commands ###
