"""add session_summaries table

Revision ID: c60a1_add_session_summaries
Revises: b59a1_add_learning_session_models
Create Date: 2026-07-29 10:04:00.000000
"""

# revision identifiers, used by Alembic.
revision = "c60a1_add_session_summaries"
down_revision = "b59a1_add_learning_session_models"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import uuid as uuid_lib


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_summaries",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("uuid", sa.String(length=36), nullable=False, unique=True, default=lambda: str(uuid_lib.uuid4())),
        sa.Column("session_id", sa.Integer(), sa.ForeignKey("learning_sessions.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("key_takeaways", sa.JSON(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("weaknesses", sa.JSON(), nullable=True),
        sa.Column("follow_up_topics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_summaries")
    # ### end Alembic commands ###
