"""create market engine

Revision ID: e6ee7e7aa129
Revises: 84a1d9bcfcce
Create Date: 2026-06-25 19:00:20.232056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ee7e7aa129'
down_revision: Union[str, None] = '84a1d9bcfcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('SESSION_COMPLETED', 'FEEDBACK_SUBMITTED', 'BADGE_AWARDED', 'TRADE_EXECUTED', 'ADMIN_UPDATE', name='market_event_type_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_event_uuid'), 'market_events', ['event_uuid'], unique=True)
    op.create_index(op.f('ix_market_events_mentor_id'), 'market_events', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_market_events_processed'), 'market_events', ['processed'], unique=False)
    op.create_table('mentor_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Float(), nullable=False),
    sa.Column('completion_score', sa.Float(), nullable=False),
    sa.Column('response_score', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('fundamentals_score', sa.Float(), nullable=False),
    sa.Column(
    'updated_at',
    sa.DateTime(timezone=True),
    server_default=sa.text('now()'),
    nullable=False
),
    sa.CheckConstraint('activity_score >= 0 AND activity_score <= 100', name='ck_activity_score'),
    sa.CheckConstraint('completion_score >= 0 AND completion_score <= 100', name='ck_completion_score'),
    sa.CheckConstraint('fundamentals_score >= 0 AND fundamentals_score <= 100', name='ck_fundamentals_score'),
    sa.CheckConstraint('rating_score >= 0 AND rating_score <= 100', name='ck_rating_score'),
    sa.CheckConstraint('response_score >= 0 AND response_score <= 100', name='ck_response_score'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_fundamentals_mentor_id'), 'mentor_fundamentals', ['mentor_id'], unique=True)
    op.create_table('mentor_market_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_supply', sa.Integer(), nullable=False),
    sa.Column('fundamentals_score', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price > 0', name='ck_base_price_positive'),
    sa.CheckConstraint('current_price >= 0', name='ck_current_price_non_negative'),
    sa.CheckConstraint('fundamentals_score >= 0 AND fundamentals_score <= 100', name='ck_market_fundamentals_score'),
    sa.CheckConstraint('market_cap >= 0', name='ck_market_cap_non_negative'),
    sa.CheckConstraint('total_supply >= 0', name='ck_total_supply_non_negative'),
    sa.CheckConstraint('version > 0', name='ck_version_positive'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_market_state_mentor_id'), 'mentor_market_state', ['mentor_id'], unique=True)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('trigger_type', sa.Enum('BUY', 'SELL', 'SESSION', 'FEEDBACK', 'BADGE', 'ADMIN', name='price_trigger_type_enum'), nullable=False),
    sa.Column('trigger_reference', sa.String(length=100), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column(
    'created_at',
    sa.DateTime(timezone=True),
    server_default=sa.text('now()'),
    nullable=False
),
    sa.CheckConstraint('market_cap >= 0', name='ck_price_history_market_cap_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_price_history_price_non_negative'),
    sa.CheckConstraint('volume >= 0', name='ck_price_history_volume_non_negative'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_mentor_id'), 'price_history', ['mentor_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='trade_type_enum'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('executed_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_price_before', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('market_price_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('executed_price > 0', name='ck_trade_price_positive'),
    sa.CheckConstraint('market_price_after >= 0', name='ck_market_price_after_non_negative'),
    sa.CheckConstraint('market_price_before >= 0', name='ck_market_price_before_non_negative'),
    sa.CheckConstraint('shares > 0', name='ck_trade_shares_positive'),
    sa.CheckConstraint('total_amount > 0', name='ck_trade_total_amount_positive'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_idempotency_key'), 'trades', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_trades_mentor_id'), 'trades', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_trades_trade_uuid'), 'trades', ['trade_uuid'], unique=True)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('user_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('shares_owned', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column(
    'updated_at',
    sa.DateTime(timezone=True),
    server_default=sa.text('now()'),
    nullable=False
),
    sa.CheckConstraint('average_buy_price >= 0', name='ck_average_buy_price_non_negative'),
    sa.CheckConstraint('invested_amount >= 0', name='ck_invested_amount_non_negative'),
    sa.CheckConstraint('realized_profit >= 0', name='ck_realized_profit_non_negative'),
    sa.CheckConstraint('shares_owned >= 0', name='ck_shares_owned_non_negative'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mentor_id', name='uq_user_mentor_holding')
    )
    op.create_index(op.f('ix_user_holdings_mentor_id'), 'user_holdings', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_user_holdings_user_id'), 'user_holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_holdings_user_id'), table_name='user_holdings')
    op.drop_index(op.f('ix_user_holdings_mentor_id'), table_name='user_holdings')
    op.drop_table('user_holdings')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_trade_uuid'), table_name='trades')
    op.drop_index(op.f('ix_trades_mentor_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_idempotency_key'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_price_history_mentor_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_mentor_market_state_mentor_id'), table_name='mentor_market_state')
    op.drop_table('mentor_market_state')
    op.drop_index(op.f('ix_mentor_fundamentals_mentor_id'), table_name='mentor_fundamentals')
    op.drop_table('mentor_fundamentals')
    op.drop_index(op.f('ix_market_events_processed'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_mentor_id'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_uuid'), table_name='market_events')
    op.drop_table('market_events')
    # ### end Alembic commands ###
