"""create learning activities table

Revision ID: ef1c8acdc42d
Revises: 13414bc20658
Create Date: 2026-07-14 16:16:00.328867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1c8acdc42d'
down_revision: Union[str, None] = '13414bc20658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_activities_user_created', 'learning_activities', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_learning_activities_user_type_created', 'learning_activities', ['user_id', 'activity_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_activities_user_id'), 'learning_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_activities_user_id'), table_name='learning_activities')
    op.drop_index('idx_learning_activities_user_type_created', table_name='learning_activities')
    op.drop_index('idx_learning_activities_user_created', table_name='learning_activities')
    op.drop_table('learning_activities')
    # ### end Alembic commands ###
