"""
RAG Prompt Models — typed request/response dataclasses (Day 72 A2).

These are pure data containers; no LLM SDK, FAISS, or database dependencies.

PromptRequest  : Input consumed by PromptBuilder.
PromptResult   : Structured prompt produced by PromptBuilder for LLMService.
GenerationResult: Final grounded answer returned by RAGService.

Security:
    - No raw embedding vectors exposed.
    - No FAISS IDs exposed.
    - No filesystem paths, API keys, or secrets exposed.
    - Sources are backend-controlled; never trusted from LLM output.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Optional

from app.rag.context_models import ContextResult, ContextSource

# Supported response styles.
# "concise"     — short, direct answer.
# "detailed"    — thorough explanation with context.
# "explanatory" — step-by-step breakdown suitable for learning.
ResponseStyle = Literal["concise", "detailed", "explanatory"]

SUPPORTED_RESPONSE_STYLES: frozenset[str] = frozenset(
    {"concise", "detailed", "explanatory"}
)


@dataclass
class PromptRequest:
    """
    Input to PromptBuilder.

    Fields:
        query          : The user's natural-language question. Must be non-empty.
        context_result : Bounded context produced by ContextBuilder.
        response_style : Optional style hint for the generation.
                         Supported: "concise" | "detailed" | "explanatory".
                         None → use settings.RAG_RESPONSE_STYLE.
    """

    query: str
    context_result: ContextResult
    response_style: Optional[str] = None


@dataclass
class PromptResult:
    """
    Structured prompt produced by PromptBuilder, ready for LLMService.

    Fields:
        system_instruction : Grounding rules and behavioral instructions for
                             the LLM.  Application-controlled.  Never contains
                             retrieved user content.
        user_message       : The full user-turn message containing the
                             bounded retrieved context (inside
                             <retrieved_context> tags) and the user query.
        sources            : Source records from ContextResult, preserved for
                             downstream attribution.  Backend-controlled.
        estimated_prompt_tokens : Approximate total prompt size in tokens.
                                  Documented as an estimate (chars // 4).
    """

    system_instruction: str
    user_message: str
    sources: list[ContextSource] = field(default_factory=list)
    estimated_prompt_tokens: int = 0


@dataclass
class GenerationResult:
    """
    Final grounded answer from RAGService.

    Fields:
        answer              : The LLM-generated answer text.  Empty string if
                              the provider returned nothing usable.
        sources             : Backend-controlled source metadata from the
                              ContextBuilder.  NOT generated by the LLM.
        model               : Model name used for generation (from settings).
        insufficient_context: True when the retrieved context did not contain
                              enough information and the system communicated this
                              to the generation layer.  The answer may then
                              contain an "insufficient knowledge" message.
        context_chunk_count : Number of context chunks that were passed to the
                              LLM.  Useful for observability.
    """

    answer: str
    sources: list[ContextSource] = field(default_factory=list)
    model: str = ""
    insufficient_context: bool = False
    context_chunk_count: int = 0
